spring:
  datasource:
    url: jdbc:mariadb://192.168.0.101:3306/testdb?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    driver-class-name: org.mariadb.jdbc.Driver
    username: wiezon
    password: wiezon1!
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.example.dsl: DEBUG
    org.apache.ibatis.logging.stdout.StdOutImpl: DEBUG